In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('houseprice.csv')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             5000 non-null   int64  
 1   income          4750 non-null   float64
 2   experience      4800 non-null   float64
 3   education       4700 non-null   str    
 4   city            4850 non-null   str    
 5   job_type        4750 non-null   str    
 6   credit_score    4650 non-null   float64
 7   loan_amount     4750 non-null   float64
 8   employment      4800 non-null   str    
 9   property_value  4700 non-null   float64
 10  rooms           4850 non-null   float64
 11  years_in_city   4800 non-null   float64
 12  house_price     5000 non-null   float64
dtypes: float64(8), int64(1), str(4)
memory usage: 507.9 KB


In [5]:
def missval(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df[col]=df[col].fillna(df[col].mode()[0])
            else:
                df[col]=df[col].fillna(df[col].mean())
    return df

In [6]:
df=missval(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             5000 non-null   int64  
 1   income          5000 non-null   float64
 2   experience      5000 non-null   float64
 3   education       5000 non-null   str    
 4   city            5000 non-null   str    
 5   job_type        5000 non-null   str    
 6   credit_score    5000 non-null   float64
 7   loan_amount     5000 non-null   float64
 8   employment      5000 non-null   str    
 9   property_value  5000 non-null   float64
 10  rooms           5000 non-null   float64
 11  years_in_city   5000 non-null   float64
 12  house_price     5000 non-null   float64
dtypes: float64(8), int64(1), str(4)
memory usage: 507.9 KB


In [7]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
def encodla(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=3:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=float)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df


In [8]:
df=encodla(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       5000 non-null   int64  
 1   income                    5000 non-null   float64
 2   experience                5000 non-null   float64
 3   education                 5000 non-null   int64  
 4   city                      5000 non-null   int64  
 5   job_type                  5000 non-null   int64  
 6   credit_score              5000 non-null   float64
 7   loan_amount               5000 non-null   float64
 8   property_value            5000 non-null   float64
 9   rooms                     5000 non-null   float64
 10  years_in_city             5000 non-null   float64
 11  house_price               5000 non-null   float64
 12  employment_Full-time      5000 non-null   float64
 13  employment_Part-time      5000 non-null   float64
 14  employment_Self-emp

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
num_col=df.select_dtypes(include=['float64','int64']).columns.drop('house_price')
df[num_col]=scaler.fit_transform(df[num_col])



In [11]:
df.head()

,age,income,experience,education,city,job_type,credit_score,loan_amount,property_value,rooms,years_in_city,house_price,employment_Full-time,employment_Part-time,employment_Self-employed
0,0.844444,0.079693,0.808511,0.666667,0.00,0.25,0.539386,0.076097,0.377343,0.400000,0.533333,388334.11,0.0,0.0,1.0
1,0.622222,0.308799,0.446809,0.000000,0.75,0.00,0.434049,0.338097,0.284933,0.495835,0.766667,455230.45,1.0,0.0,0.0
2,0.311111,0.281093,0.276596,0.666667,0.00,1.00,0.784939,0.431076,0.537068,0.400000,0.233333,473574.88,1.0,0.0,0.0
3,0.933333,0.588796,0.744681,0.666667,0.75,0.25,0.595057,0.445361,0.510251,0.000000,0.166667,548769.66,1.0,0.0,0.0
4,0.155556,0.206738,0.127660,0.000000,0.25,0.75,0.616309,0.630131,0.000000,0.800000,0.500000,257429.67,1.0,0.0,0.0


In [12]:
from sklearn.model_selection import train_test_split
x=df.drop('house_price',axis=1)
y=df['house_price']

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [18]:
lr.fit(x_train,y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](14,)","[36462.26,45045.77,62515.04,..., 903.82, -836.96, -66.86]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](14,)","['age','income','experience',...,'employment_Full-time', 'employment_Part-time','employment_Self-employed']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,1.73e+05
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,14
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int,13


In [19]:
y_pred=lr.predict(x_test)
y_pred

array([444142.68887235, 476870.60787627, 370240.77238126, 479653.78231339,
       476359.26879937, 480050.25798059, 422430.51137356, 396482.06669202,
       392849.41528829, 539789.53887636, 633893.97647995, 493514.07669283,
       477111.85279441, 350201.98110534, 603653.40892281, 425369.22244781,
       519730.17241479, 377848.3788936 , 415992.29499514, 559837.9103574 ,
       408434.1057644 , 426361.88250258, 525968.77080382, 372017.58213506,
       475303.91324882, 511559.87453835, 482735.04587159, 476654.40488835,
       502367.34332931, 465988.95416207, 459609.81494826, 514891.37037528,
       435621.94388828, 473523.77450591, 337069.76183993, 479589.30625038,
       368036.49272066, 455688.26029996, 470742.09270159, 434169.85195606,
       508411.52959027, 523140.36497164, 594597.71222518, 470474.41213548,
       520886.34094469, 450229.9932854 , 469613.23205291, 469671.40853748,
       497569.39262859, 533864.6511161 , 395975.5152113 , 515996.3112567 ,
       376735.048299  , 4

In [27]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [28]:

print("MAE:", mae),
print("MSE:", mse),
print("R2 Score:", r2)

MAE: 30951.365971969728
MSE: 1548297095.4341044
R2 Score: 0.7870513138596583


In [32]:
from sklearn.model_selection import KFold,cross_val_score
kf=KFold(n_splits=5,shuffle=True,random_state=42)
scores=cross_val_score(lr,x,y,cv=kf,scoring='r2')
print(scores)

[0.78705131 0.76641609 0.75761581 0.76274364 0.75537881]


In [33]:
import numpy as np
np.mean(scores)

np.float64(0.7658411328039728)

In [34]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()

In [35]:
dtr.fit(x_train,y_train)

,"criterion criterion: {""squared_error"", ""absolute_error"", ""poisson""}, default=""squared_error""The function to measure the quality of a split. Supported criteriaare ""squared_error"" for the mean squared error, which is equal tovariance reduction as feature selection criterion and minimizes the L2loss using the mean of each terminal node, ""absolute_error"" for the meanabsolute error, which minimizes the L1 loss using the median of each terminalnode, and ""poisson"" which uses reduction in Poisson deviance to find splits,also using the mean of each terminal node... versionadded:: 0.18 Mean Absolute Error (MAE) criterion... versionadded:: 0.24 Poisson deviance criterion... versionchanged:: 1.9 Criterion `""friedman_mse""` was deprecated.",'squared_error'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.For an example of how ``max_depth`` influences the model, see:ref:`sphx_glr_auto_examples_tree_plot_tree_regression.py`.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary <random_state>` for details.",None
,"max_leaf_node

In [37]:
y_pred=dtr.predict(x_test)
y_pred

array([437094.69, 481910.76, 347611.75, 443917.35, 371351.3 , 371174.4 ,
       347611.75, 412380.87, 539739.79, 615980.08, 614392.79, 413814.8 ,
       419844.7 , 352321.65, 611404.25, 452463.24, 531694.74, 404917.65,
       255778.38, 557736.53, 407709.6 , 398881.9 , 574515.05, 349601.72,
       411050.08, 478459.39, 444495.91, 520787.09, 472160.74, 506632.15,
       451967.88, 482931.91, 396320.52, 506643.61, 380438.44, 521580.22,
       346839.08, 434827.47, 475417.92, 426792.99, 580528.13, 578940.9 ,
       555512.94, 505322.35, 546091.06, 465896.05, 455108.72, 441602.08,
       531913.2 , 532748.47, 382229.42, 537105.48, 345169.35, 434827.47,
       463943.49, 555512.94, 283500.3 , 505156.71, 524692.09, 589841.49,
       509120.75, 543173.95, 599193.77, 581047.49, 562331.28, 351633.62,
       460744.46, 260674.35, 630316.18, 366799.31, 417285.37, 484898.19,
       595366.73, 491186.09, 400052.26, 425942.24, 342599.03, 532957.44,
       558374.  , 292927.89, 504121.12, 353560.52, 

In [43]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [44]:
print("MAE:", mae),
print("MSE:", mse),
print("R2 Score:", r2)

MAE: 46946.16246
MSE: 3536646999.221373
R2 Score: 0.5135789287163806


In [45]:
from sklearn.model_selection import KFold,cross_val_score
kf=KFold(n_splits=5,shuffle=True,random_state=42)
scores=cross_val_score(dtr,x,y,cv=kf,scoring='r2')

In [46]:
print(scores)

[0.52131867 0.5235462  0.48257083 0.43400682 0.48063838]


In [47]:
np.mean(scores)

np.float64(0.48841617752665617)

In [48]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor()
rfr

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""squared_error"", ""absolute_error"", ""poisson""}, default=""squared_error""The function to measure the quality of a split. Supported criteriaare ""squared_error"" for the mean squared error, which is equal tovariance reduction as feature selection criterion and minimizes the L2loss using the mean of each terminal node, ""absolute_error"" for the meanabsolute error, which minimizes the L1 loss using the median of each terminalnode, and ""poisson"" which uses reduction in Poisson deviance to find splits,also using the mean of each terminal node... versionadded:: 0.18 Mean Absolute Error (MAE) criterion... versionadded:: 1.0 Poisson criterion... versionchanged:: 1.9 Criterion `""friedman_mse""` was deprecated.",'squared_error'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=1.0The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None or 1.0, then `max_features=n_features`... note:: The default of 1.0 is equivalent to bagged trees and more randomness can be achieved by setting smaller values, e.g. 0.3... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to 1.0.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",1.0
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the numb

In [49]:
rfr.fit(x_train,y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""squared_error"", ""absolute_error"", ""poisson""}, default=""squared_error""The function to measure the quality of a split. Supported criteriaare ""squared_error"" for the mean squared error, which is equal tovariance reduction as feature selection criterion and minimizes the L2loss using the mean of each terminal node, ""absolute_error"" for the meanabsolute error, which minimizes the L1 loss using the median of each terminalnode, and ""poisson"" which uses reduction in Poisson deviance to find splits,also using the mean of each terminal node... versionadded:: 0.18 Mean Absolute Error (MAE) criterion... versionadded:: 1.0 Poisson criterion... versionchanged:: 1.9 Criterion `""friedman_mse""` was deprecated.",'squared_error'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=1.0The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None or 1.0, then `max_features=n_features`... note:: The default of 1.0 is equivalent to bagged trees and more randomness can be achieved by setting smaller values, e.g. 0.3... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to 1.0.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",1.0
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the numb

In [51]:
y_pred=rfr.predict(x_test)
y_pred

array([448595.6001, 450649.0961, 395246.1009, 489120.853 , 519598.9061,
       468085.8129, 406963.8418, 395666.3544, 414315.2928, 557126.6339,
       595326.8303, 482930.7128, 444270.9686, 349638.3086, 612226.62  ,
       426789.9665, 516895.5974, 384393.1195, 383597.5566, 554207.3476,
       403430.6477, 421497.3818, 543229.3525, 375428.5931, 487558.4883,
       509693.5135, 471383.9401, 470859.5604, 516660.6079, 495546.5698,
       472451.6771, 493202.1599, 443843.4083, 463026.4647, 331899.5905,
       493796.8742, 369413.783 , 450865.0725, 444256.6406, 449089.8706,
       502030.5215, 514299.0281, 592152.8581, 443101.3664, 526789.2092,
       468249.0952, 482475.7779, 454850.0708, 502650.1745, 545147.7963,
       396791.3384, 510187.9438, 381140.0656, 464796.4703, 420067.3693,
       571219.8336, 361230.1611, 477977.4028, 455951.8642, 545717.8274,
       505507.527 , 522711.5764, 521468.6167, 455686.8171, 615262.0936,
       350473.452 , 459163.8568, 359561.2795, 596227.1669, 42150

In [52]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [53]:
print("MAE:", mae),
print("MSE:", mse),
print("R2 Score:", r2)

MAE: 32445.507579000005
MSE: 1675523855.3766196
R2 Score: 0.769552881903965


In [54]:
from sklearn.model_selection import KFold,cross_val_score
kf=KFold(n_splits=5,shuffle=True,random_state=42)
scores=cross_val_score(rfr,x,y,cv=kf,scoring='r2')

In [55]:
print(scores)

[0.77323619 0.75606228 0.74397435 0.74106368 0.73842044]


In [56]:
np.mean(scores)

np.float64(0.7505513903175421)

In [57]:
from sklearn.svm import SVR
svr=SVR(kernel='linear',C=1.0)

In [58]:
svr.fit(x_train,y_train)

,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm.If none is given, 'rbf' will be used. If a callable is given it isused to precompute the kernel matrix.For an intuitive visualization of different kernel typessee :ref:`sphx_glr_auto_examples_svm_plot_svm_regression.py`",'linear'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive.The penalty is a squared l2. For an intuitive visualization of theeffects of scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"epsilon epsilon: float, default=0.1Epsilon in the epsilon-SVR model. It specifies the epsilon-tubewithin which no penalty is associated in the training loss functionwith points predicted within a distance epsilon from the actualvalue. Must be non-negative.",0.1
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide <shrinking_svm>`.",True
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False
,"max_iter max_iter: int, default=-1Hard limit on iterations within solver, or -1 for no limit.",-1


In [59]:
y_pred=svr.predict(x_test)
y_pred

array([455147.54292947, 455065.88182004, 454721.4953944 , 455064.46809922,
       455167.22146647, 455356.60416855, 454908.30766814, 454921.95050725,
       454738.21736572, 455253.50700685, 455084.12921038, 454946.26611409,
       454912.29592183, 454788.68719071, 455422.91302383, 454998.36499926,
       455180.23634614, 454710.39738618, 454959.23832094, 455375.69628666,
       455042.97488223, 455082.9396495 , 455219.83228483, 454643.15080409,
       454953.85360686, 455345.12597971, 455292.29488999, 455378.16767864,
       455217.45005403, 454925.37569766, 454939.47264645, 455103.38357956,
       455008.75765341, 455152.39314343, 454790.19254862, 455010.26359064,
       454780.26541539, 455045.55599497, 455030.69708758, 454980.45854917,
       455188.89299924, 455300.38887463, 455385.68190628, 455176.71789404,
       455312.21314894, 455008.07998546, 455174.5397648 , 455194.90834309,
       455127.81854547, 455229.44770756, 454857.96372543, 455225.5761653 ,
       454865.0036232 , 4

In [60]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [61]:
print("MAE:", mae),
print("MSE:", mse),
print("R2 Score:", r2)

MAE: 68927.50146576142
MSE: 7248158099.883543
R2 Score: 0.003107511562617571


In [65]:
from sklearn.model_selection import KFold,cross_val_score
kf=KFold(n_splits=5,shuffle=True,random_state=42)
print(scores)

[0.77323619 0.75606228 0.74397435 0.74106368 0.73842044]


In [66]:
np.mean(scores)

np.float64(0.7505513903175421)

In [68]:
from tabulate import tabulate
results=[
    ['LinearRegression',0.7658],
    ['DecisionTreeRegressor',0.4884],
    ['RandomForestRegressor',0.7505],
    ['SVR',0.7505]
]
headers=['Algorithm','Accuracy score']
table=tabulate(results,headers=headers,tablefmt='grid',floatfmt='.2f')
print(table)

+-----------------------+------------------+
| Algorithm             |   Accuracy score |
+=======================+==================+
| LinearRegression      |             0.77 |
+-----------------------+------------------+
| DecisionTreeRegressor |             0.49 |
+-----------------------+------------------+
| RandomForestRegressor |             0.75 |
+-----------------------+------------------+
| SVR                   |             0.75 |
+-----------------------+------------------+


In [71]:
import matplotlib.pyplot as plt

In [72]:
df.head()

,age,income,experience,education,city,job_type,credit_score,loan_amount,property_value,rooms,years_in_city,house_price,employment_Full-time,employment_Part-time,employment_Self-employed
0,0.844444,0.079693,0.808511,0.666667,0.00,0.25,0.539386,0.076097,0.377343,0.400000,0.533333,388334.11,0.0,0.0,1.0
1,0.622222,0.308799,0.446809,0.000000,0.75,0.00,0.434049,0.338097,0.284933,0.495835,0.766667,455230.45,1.0,0.0,0.0
2,0.311111,0.281093,0.276596,0.666667,0.00,1.00,0.784939,0.431076,0.537068,0.400000,0.233333,473574.88,1.0,0.0,0.0
3,0.933333,0.588796,0.744681,0.666667,0.75,0.25,0.595057,0.445361,0.510251,0.000000,0.166667,548769.66,1.0,0.0,0.0
4,0.155556,0.206738,0.127660,0.000000,0.25,0.75,0.616309,0.630131,0.000000,0.800000,0.500000,257429.67,1.0,0.0,0.0
